---
- name: Install Apache and PHP
  become: true
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - httpd
    - php-fpm

- name: Install a phpinfo file on the HTTP directory
  copy:
    dest: /var/www/html/phpinfo.php
    content: |
      <?php
      phpinfo();
      ?>
    owner: apache
    group: apache
    mode: 0664

- name: Open the firewall for HTTP
  firewalld:
    service: http
    state: enabled
    permanent: true

- name: Run Apache
  systemd:
    name: httpd
    state: stopped
    enabled: false

