#!/bin/bash

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -h, --help          Show this help message and exit"
    echo "      --no-headers    Do not print the header row"
    echo "  -w, --web           Create a web page with the output instead of printing to the console"
}

header="NAME z/VM-ID"

if ! TEMP="$(getopt -o 'hw' -l 'no-headers,help,web' -n "zvmguests" -- "$@")"; then
    usage
    exit 99
fi

eval "set -- ${TEMP}"
unset TEMP

while true; do
    case "$1" in
        '--no-headers')
            header=""
            shift
            continue
        ;;
        '-w'|'--web')
            action="web"
            shift
            continue
        ;;
        '-h'|'--help')
            usage
            exit 1
        ;;
        '--')
            if [[ -n $2 ]]; then
                echo "Extra parameter(s) provided!"
                exit 3
            fi
            break
        ;;
        *)
            exit 99
        ;;
    esac
done

authtoken=$(curl -s -k -i https://icicmgt1.z.stg.ibm:5000/v3/auth/tokens \
  -H "Content-Type: application/json" \
  -H "Vary: X-Auth-Token, X-Subject-Token" \
  -H "Accept: application/json" \
  -d '{"auth":{"scope":{"project":{"domain":{"name":"Default"},"name":"ibm-default"}},
       "identity":{"password":{"user":{"domain":{"name":"Default"},"password":"lnx4vm","name":"root"}},"methods":["password"]}}
}' | grep -i X-Subject-Token | awk '{print $2;}' )

tfservers=$(TF_CLI_CONFIG_FILE=.terraform.rc /opt/go/bin/terraform output -json | jq '.[].value |.[]| .vm_name '| paste -sd, -)

guests=$(curl -s -k https://icicmgt1.z.stg.ibm:8774/v2.1/205d7f7dc28c4de692df3acc7439485f/servers/detail \
        -H "X-Auth-Token: ${authtoken}" \
        | jq -r --argjson tfservers "[${tfservers}]" ' .servers[] | select([.name] | inside($tfservers)) | "\(.name) \(.["OS-EXT-SRV-ATTR:instance_name"])"' )
if [[ -z "$guests" ]]; then
    header="No deployed guests found."
else
    lbip=$(TF_CLI_CONFIG_FILE=.terraform.rc /opt/go/bin/terraform output -json haproxy_instances | jq -r '.vm1.ip_address')
fi

if [[ "$action" == "web" ]]; then
    echo "<!DOCTYPE html>" > zvmguests.html
    echo "<html lang=\"en\"><head><meta charset=\"UTF-8\">" >> zvmguests.html
    echo "<style>body { font-family: \"IBM Plex Sans\", Helvetica, Arial, sans-serif; margin: 20px; } h1 { color: #333; } pre { background-color: #f4f4f4; padding: 10px; border-radius: 5px; } a { color: #007BFF; text-decoration: none; } a:hover { text-decoration: underline; }</style>" >> zvmguests.html
    echo "<title>z/VM Guests by Terraform and ICIC</title></head><body>" >> zvmguests.html
    echo "<h1>z/VM Guests by Terraform and ICIC</h1><p>The z/VM guests currently managed by Terraform are listed below:</p>" >> zvmguests.html
    echo "<pre>" >> zvmguests.html
    (echo "${header}" && echo "${guests}") | column -t >> zvmguests.html
    echo "</pre>" >> zvmguests.html
    echo "<h2>Demo pages</h2><ul>" >> zvmguests.html
    if [[ -n "${guests}" ]]; then
        echo "<li>HAProxy <a href=\"http://${lbip}:8404/stats\">stats page</a></li>" >> zvmguests.html
        echo "<li>Sophisticated PHP-based web app <a href=\"http://${lbip}/phpinfo.php\">demo page</a></li>" >> zvmguests.html
    else
        echo "<li>No guests deployed, so no demo pages available.</li>" >> zvmguests.html
    fi
    echo "</ul>" >> zvmguests.html
    echo '<h2>Terraform graph:</h2><div style="display: flex;">' >> zvmguests.html
    TF_CLI_CONFIG_FILE=.terraform.rc /opt/go/bin/terraform graph | dot -Tsvg >> zvmguests.html
    echo "</div>" >> zvmguests.html
    echo "<p>Generated on $(date)</p>" >> zvmguests.html
    echo "<h3>Note:</h3><p>This page is generated by a script and may not reflect real-time data. For the most current information, please refer to the Terraform state or the z/VM management console.</p>" >> zvmguests.html
    echo "</body></html>" >> zvmguests.html
    echo "Web page created: zvmguests.html"
    exit 0
else
    ([[ -z ${header} ]] || echo "${header}" && echo "${guests}") | column -t
fi


# Invalidate the token
curl -s -k https://icicmgt1.z.stg.ibm:5000/v3/auth/tokens \
        -H "X-Auth-Token: ${authtoken}" \
        -H "X-Subject-Token: ${authtoken}" -X DELETE
