#!/bin/bash

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  -h, --help          Show this help message and exit"
    echo "      --no-headers    Do not print the header row"
    echo "  -s, --status        Print the status of the VMs instead of their z/VM IDs"
    echo "  -w, --web           Create a web page with the output instead of printing to the console"
}

header="NAME z/VM-ID"

if ! TEMP="$(getopt -o 'hsw' -l 'no-headers,help,status,web' -n "zvmguests" -- "$@")"; then
    echo "Terminating."
    exit 99
fi

eval "set -- ${TEMP}"
unset TEMP

while true; do
    case "$1" in
        '--no-headers')
            header=""
            shift
            continue
        ;;
        '-w'|'--web')
            action="web"
            shift
            continue
        ;;
        '-h'|'--help')
            usage
            exit 1
        ;;
        '-s'|'--status')
            action="isq"
            shift
            continue
        ;;
        '--')
            if [[ -n $2 ]]; then
                echo "Extra parameter(s) provided!"
                exit 3
            fi
            break
        ;;
        *)
            exit 99
        ;;
    esac
done

authtoken=$(curl -s -k -i https://icicmgt1.z.stg.ibm:5000/v3/auth/tokens \
  -H "Content-Type: application/json" \
  -H "Vary: X-Auth-Token, X-Subject-Token" \
  -H "Accept: application/json" \
  -d '{"auth":{"scope":{"project":{"domain":{"name":"Default"},"name":"ibm-default"}},
       "identity":{"password":{"user":{"domain":{"name":"Default"},"password":"lnx4vm","name":"root"}},"methods":["password"]}}
}' | grep -i X-Subject-Token | awk '{print $2;}' )

tfservers=$(TF_CLI_CONFIG_FILE=.terraform.rc /opt/go/bin/terraform output -json | jq '.[].value |.[]| .vm_name '| paste -sd, -)

guests=$(curl -s -k https://icicmgt1.z.stg.ibm:8774/v2.1/205d7f7dc28c4de692df3acc7439485f/servers/detail \
        -H "X-Auth-Token: ${authtoken}" \
        | jq -r --argjson tfservers "[${tfservers}]" ' .servers[] | select([.name] | inside($tfservers)) | "\(.name) \(.["OS-EXT-SRV-ATTR:instance_name"])"' )

if [[ "$action" == "web" ]]; then
    echo "<html><head><title>z/VM Guests in Terraform</title></head><body>" > zvmguests.html
    echo "<h1>z/VM Guests in Terraform</h1><p>The z/VM guests currently managed by Terraform are listed below:</p>" >> zvmguests.html
    echo "<pre>" >> zvmguests.html
    (echo "${header}" && echo "${guests}") | column -t >> zvmguests.html
    echo '</pre><h2>Terraform graph:</h2><div style="display: flex;">' >> zvmguests.html
    TF_CLI_CONFIG_FILE=.terraform.rc /opt/go/bin/terraform graph | dot -Tsvg >> zvmguests.html
    echo "</div>" >> zvmguests.html
    echo "<p>Generated on $(date)</p>" >> zvmguests.html
    echo "<h3>Note:</h3><p>This page is generated by a script and may not reflect real-time data. For the most current information, please refer to the Terraform state or the z/VM management console.</p>" >> zvmguests.html
    echo "</body></html>" >> zvmguests.html
    echo "Web page created: zvmguests.html"
    exit 0
else
    ([[ -z ${header} ]] || echo "${header}" && echo "${guests}") | column -t
fi


# Invalidate the token
curl -s -k https://icicmgt1.z.stg.ibm:5000/v3/auth/tokens \
        -H "X-Auth-Token: ${authtoken}" \
        -H "X-Subject-Token: ${authtoken}" -X DELETE
