- name: Generate the HAProxy config
  ansible.builtin.set_fact:
    haproxy_content: "{{ lookup('template', 'templates/haproxy.cfg.j2') }}"
  vars:
    jsonquery: "[values(@)]|[]"

- name: Add custom HAProxy configuration
  ansible.builtin.blockinfile:
    dest: /etc/haproxy/haproxy.cfg
    insertafter: EOF
    content: '{{ haproxy_content }}'

- name: Update FirewallD
  ansible.posix.firewalld:
    port: 8200/tcp
    state: enabled
    immediate: true
    permanent: true

- name: Restart HAProxy
  ansible.builtin.systemd:
    service: haproxy
    state: restarted
