- name: HAProxy Configuration
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Gather Terraform facts
      cloud.terraform.terraform_output:
        name: httpd_instances
    - name: "Include HAProxy tasks"
      include_tasks: haproxy.yml

